# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
orbs:
  maven: circleci/maven@1.4.1
jobs:
  run-all-test:
    steps:
      - checkout
      - run:
          name: "run all the test"
          command: "mvn test"
# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  riceCookerTest:
    jobs:
      - maven/test
      - run-all-test
